# Generated by maven-r-jsr223-plugin: do not edit by hand
# returns a reference to a java class in a jsr223 engine
JavaApi = R6::R6Class("JavaApi", public=list( 
	#### fields ----
	.engine = NULL,
	.objId = 0,
	CitationGraph = NULL,
  
 	#### constructor ----
 	initialize = function() {
	
	# initialise java engine
	
	class.path <- c(
		system.file("java", "groovy-all-2.4.17.jar", package="jlitrev"),
		system.file("java", "literature-graph-master-SNAPSHOT-jar-with-dependencies.jar", package="jlitrev")
	)	
	self$.engine = jsr223::ScriptEngine$new("groovy", class.path)
	self$.engine$setDataFrameRowMajor(FALSE)
	# set up engine
	self$.engine %@% '
		objs = [];
		nextObjId = 0;
	'
	
	# initialise constructor and static class definitions
	self$CitationGraph = list(
		new = function(secrets, graphDb, graphConf, working, output) {
			# constructor
			# copy parameters
		self$.engine$tmp_secrets = secrets; # copy parameter by value
		self$.engine$tmp_graphDb = graphDb; # copy parameter by value
		self$.engine$tmp_graphConf = graphConf; # copy parameter by value
		self$.engine$tmp_working = working; # copy parameter by value
		self$.engine$tmp_output = output; # copy parameter by value
			objId = self$.engine %~% '
				synchronized(objs) {
					objs[nextObjId] = new uk.co.terminological.literaturereview.CitationGraph(tmp_secrets, tmp_graphDb, tmp_graphConf, tmp_working, tmp_output);
					nextObjId = nextObjId+1 
				}
				return nextObjId-1;
			'
			# delete parameters
			self$.engine$remove("tmp_secrets")
			self$.engine$remove("tmp_graphDb")
			self$.engine$remove("tmp_graphConf")
			self$.engine$remove("tmp_working")
			self$.engine$remove("tmp_output")
			return(CitationGraph$new(self$.engine, objId))
		}	,
		fromPropertyFile = function(propFilename) {
			# copy parameters
			self$.engine$tmp_propFilename = propFilename; # by value
			#execute static call
			# execute static method and return object by reference (always creates a new instance)   
			objId = self$.engine %~% '
				synchronized(objs) {
					objs[nextObjId] = uk.co.terminological.literaturereview.CitationGraph.fromPropertyFile(tmp_propFilename);
					nextObjId = nextObjId+1 
				}
				return nextObjId-1;
			'
			# wrap resulting id in R class - static methods always create instances
			out = CitationGraph$new(self$.engine, objId)
			# delete parameters
			self$.engine$remove("tmp_propFilename")
			return(out)
		}	)
	}
))

## a generic catch all object reference for classes that cannot be mapped to and from Java.
Object = R6::R6Class("Object", public=list(
	.engine = NULL,
	.objId = NULL,
	initialize = function(engine,objectId){
		self$.engine = engine;
		self$.objId = objectId;
	},
	print = function() {
		self$.engine$tmp2_objId = self$.objId;
		out = self$.engine %~% '
			return objs[tmp2_objId].toString();
		'
		self$.engine$remove("tmp2_objId")
		print(out)
		invisible(self)
	}
))

CitationGraph = R6::R6Class("CitationGraph", public=list(
	.engine = NULL,
	.objId = NULL,
	initialize = function(engine,objectId){
		self$.engine = engine;
		self$.objId = objectId;
	},
	analser = function() {
		# copy parameters
		self$.engine$tmp2_objId = self$.objId;
		#execute call on instance .objId returning a new (or the same) objId by reference   
		objId = self$.engine %~% '
			def tmp = objs[tmp2_objId].analser();
			// if the result the same object as the original? e.g. a fluent method
			if (tmp.is(objs[tmp2_objId])) {
				return tmp2_objId; 
			} else {
				synchronized(objs) {
					objs[nextObjId] = tmp;
					nextObjId = nextObjId+1; 
				}
				return nextObjId-1;
			}
		'
		# delete parameters
		self$.engine$remove("tmp2_objId")
		if (objId == self$.objId) {
			invisible(self) # e.g. a fluent method
		} else {
			out = Object$new(self$.engine, objId)
			return(out)
		}
	},
	shutdown = function() {
		# copy parameters
		self$.engine$tmp2_objId = self$.objId;
		#execute call on instance .objId returning a new (or the same) objId by reference   
		objId = self$.engine %~% '
			def tmp = objs[tmp2_objId].shutdown();
			// if the result the same object as the original? e.g. a fluent method
			if (tmp.is(objs[tmp2_objId])) {
				return tmp2_objId; 
			} else {
				synchronized(objs) {
					objs[nextObjId] = tmp;
					nextObjId = nextObjId+1; 
				}
				return nextObjId-1;
			}
		'
		# delete parameters
		self$.engine$remove("tmp2_objId")
		invisible(NULL)
	},
	buildFromPropertyFile = function(propFilename) {
		# copy parameters
		self$.engine$tmp_propFilename = propFilename; # pass parameter by value
		self$.engine$tmp2_objId = self$.objId;
		#execute call on instance .objId returning a new (or the same) objId by reference   
		objId = self$.engine %~% '
			def tmp = objs[tmp2_objId].buildFromPropertyFile(tmp_propFilename);
			// if the result the same object as the original? e.g. a fluent method
			if (tmp.is(objs[tmp2_objId])) {
				return tmp2_objId; 
			} else {
				synchronized(objs) {
					objs[nextObjId] = tmp;
					nextObjId = nextObjId+1; 
				}
				return nextObjId-1;
			}
		'
		# delete parameters
		self$.engine$remove("tmp2_objId")
		self$.engine$remove("tmp_propFilename")
		invisible(NULL)
	},
	build = function(search, broaderSearch, earliest, latest) {
		# copy parameters
		self$.engine$tmp_search = search; # pass parameter by value
		self$.engine$tmp_broaderSearch = broaderSearch; # pass parameter by value
		self$.engine$tmp_earliest = earliest; # pass parameter by value
		self$.engine$tmp_latest = latest; # pass parameter by value
		self$.engine$tmp2_objId = self$.objId;
		#execute call on instance .objId returning a new (or the same) objId by reference   
		objId = self$.engine %~% '
			def tmp = objs[tmp2_objId].build(tmp_search, tmp_broaderSearch, tmp_earliest, tmp_latest);
			// if the result the same object as the original? e.g. a fluent method
			if (tmp.is(objs[tmp2_objId])) {
				return tmp2_objId; 
			} else {
				synchronized(objs) {
					objs[nextObjId] = tmp;
					nextObjId = nextObjId+1; 
				}
				return nextObjId-1;
			}
		'
		# delete parameters
		self$.engine$remove("tmp2_objId")
		self$.engine$remove("tmp_search")
		self$.engine$remove("tmp_broaderSearch")
		self$.engine$remove("tmp_earliest")
		self$.engine$remove("tmp_latest")
		invisible(NULL)
	},
	print = function() {
		self$.engine$tmp2_objId = self$.objId;
		out = self$.engine %~% '
			return objs[tmp2_objId].toString();
		'
		self$.engine$remove("tmp2_objId")
		print(out)
		invisible(self)
	}
))

